Include pyproject.toml in Dockerfile's dep_builder
stac-utils/stactools pull request #157
Opened 2021-07-13 20:36 UTC by gadomski

Required with newer pip versions. See https://github.com/pypa/pip/pull/9945 for some related discussion.

2021-07-14 00:14 UTC, cuttlefish requested changes

2021-07-14 00:14 UTC, cuttlefish commented on docker/Dockerfile
> +COPY pyproject.toml ./
```suggestion
COPY pyproject.toml setup.cfg ./
```

2021-07-14 04:34 UTC, cuttlefish approved these changes

2021-07-14 04:39 UTC, cuttlefish commented
@gadomski Apparently I added it in stactools-packages/template but not here. Thanks for spotting it!

2021-07-15 15:00 UTC, lossyrob approved these changes

2021-07-15 15:05 UTC, merged