Allow geometries to be computed from multiple asset footprints
stac-utils/stactools pull request #445
Opened 2023-06-27 21:51 UTC by jpolchlo

**Related Issue(s):**
#392 

**Description:**
This PR extends `update_geometry_from_asset_footprint()` to have more flexibility in how the footprint is derived in the event of multiple, non-coincident asset footprints.  Previously, this method would simply take the first matching asset footprint.  This PR allows for the footprint to be the intersection or union of the matching assets.  Adding the intersection was an executive decision, since I can imagine wanting to build STACs for analysis where we want to be sure data is present for all assets to avoid needing to filter for NODATA in subsequent steps.  If this doesn't make sense, it can be removed in favor of only using the union.

**PR checklist:**

- [x] Code is formatted (run `scripts/format`).
- [x] Code lints properly (run `scripts/lint`).
- [ ] Tests pass (run `scripts/test`).
- [ ] Documentation has been updated to reflect changes, if applicable.
- [ ] Changes are added to the [CHANGELOG](../CHANGELOG.md).

2023-06-27 21:52 UTC, jpolchlo commented
This PR needs an improved test.  I'm in the market for a good sample Item to base it on.

2023-06-28 11:43 UTC, gadomski requested changes
As mentioned, needs a test case.

2023-06-28 11:43 UTC, gadomski commented on src/stactools/core/utils/raster_footprint.py
> +            elif footprint_aggregator == "union":
Should be an enum.

2023-06-29 16:34 UTC, gadomski approved these changes

2023-06-29 18:42 UTC, jpolchlo commented
I realized too late that the baseline for the test here should have been derived from rasters that indicate the union/intersection.  Not worth holding up the show, though.  Merging this, but making this comment for posterity.

2023-06-29 18:42 UTC, merged